### PR TITLE
[Package] add fcl_catkin

### PR DESCRIPTION
**Pull request by Amos-Chen98**

### CODE REVIEW

**Comment by sugikazu75** [comment]
@Amos-Chen98 
Hi, thank you for your PR.
In my understanding, this PR adds catkinized fcl library, however, there already exist `hpp-fcl`  https://github.com/sugikazu75/ros-o-builder/blob/fee16e0d0b1951117d1ae0802252d44cd7dd1e18/sources.repos#L274-L277

Moreover, `fcl_catkin` seems not to be so common ros package to release. Do you want to release this package to apt because it takes a long time to build, or for some other reason?

**Comment by Amos-Chen98** [comment]
Hello @sugikazu75 !
It's nice to know hpp-fcl (now as coal). I will take a look at this package. It might benefit my ongoing work.
As for `fcl_catkin`, I'd like to release it because it is required by this repo:
https://github.com/ut-dragon-lab/motion_planning/blob/89e1108b95697de0d7464044c3449f2604812936/aerial_motion/differential_kinematics/package.xml#L30

**Comment by sugikazu75** [comment]
OK I understood. 
I found `fcl_catkin` is released for noetic
```
$ apt search fcl_catkin
Sorting... Done
Full Text Search... Done
ros-noetic-fcl-catkin/focal 0.6.1-1focal.20220516.060922 amd64
  fcl_catkin
```
so I will add this package for ROS-O.

**Comment by sugikazu75** [comment]
HI, I picked your PR and started build process. 
About 15hours later, it will be released if there are no build errors.

**Pull request closed without merging**
